<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-OMFBO4B" name="demo" tests="8" failures="1" timestamp="26 Sep 2018 04:42:45 GMT" time="0.021" errors="0">
  <testcase name="div" time="0.005" classname="calculator.calcy3"/>
  <testcase name="mult" time="0.0" classname="calculator.calcy3"/>
  <testcase name="sub" time="0.0" classname="calculator.calcy3"/>
  <testcase name="sum" time="0.0" classname="calculator.calcy3"/>
  <testcase name="div" time="0.001" classname="calculator.calcy4">
    <failure type="java.lang.AssertionError" message="expected [2] but found [0]">
      <![CDATA[java.lang.AssertionError: expected [2] but found [0]
	at calculator.calcy4.div(calcy4.java:44)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:383)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:344)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:125)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:417)
... Removed 26 stack frames]]>
    </failure>
  </testcase> <!-- div -->
  <testcase name="mult" time="0.0" classname="calculator.calcy4"/>
  <testcase name="sub" time="0.0" classname="calculator.calcy4"/>
  <testcase name="sum" time="0.0" classname="calculator.calcy4"/>
</testsuite> <!-- demo -->
