<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="8" passed="7">
  <reporter-output>
  </reporter-output>
  <suite name="mavendemo" duration-ms="21" started-at="2018-09-26T04:42:45Z" finished-at="2018-09-26T04:42:45Z">
    <groups>
    </groups>
    <test name="demo" duration-ms="21" started-at="2018-09-26T04:42:45Z" finished-at="2018-09-26T04:42:45Z">
      <class name="calculator.calcy3">
        <test-method status="PASS" signature="div()[pri:0, instance:calculator.calcy3@54a097cc]" name="div" duration-ms="5" started-at="2018-09-26T10:12:45Z" finished-at="2018-09-26T10:12:45Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- div -->
        <test-method status="PASS" signature="sub()[pri:0, instance:calculator.calcy3@54a097cc]" name="sub" duration-ms="0" started-at="2018-09-26T10:12:45Z" finished-at="2018-09-26T10:12:45Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- sub -->
        <test-method status="PASS" signature="mult()[pri:0, instance:calculator.calcy3@54a097cc]" name="mult" duration-ms="0" started-at="2018-09-26T10:12:45Z" finished-at="2018-09-26T10:12:45Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- mult -->
        <test-method status="PASS" signature="sum()[pri:0, instance:calculator.calcy3@54a097cc]" name="sum" duration-ms="0" started-at="2018-09-26T10:12:45Z" finished-at="2018-09-26T10:12:45Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- sum -->
      </class> <!-- calculator.calcy3 -->
      <class name="calculator.calcy4">
        <test-method status="FAIL" signature="div()[pri:0, instance:calculator.calcy4@3567135c]" name="div" duration-ms="1" started-at="2018-09-26T10:12:45Z" finished-at="2018-09-26T10:12:45Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [2] but found [0]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [2] but found [0]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:370)
	at org.testng.Assert.assertEquals(Assert.java:380)
	at calculator.calcy4.div(calcy4.java:44)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:383)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:344)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:125)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:417)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- div -->
        <test-method status="PASS" signature="mult()[pri:0, instance:calculator.calcy4@3567135c]" name="mult" duration-ms="0" started-at="2018-09-26T10:12:45Z" finished-at="2018-09-26T10:12:45Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- mult -->
        <test-method status="PASS" signature="sub()[pri:0, instance:calculator.calcy4@3567135c]" name="sub" duration-ms="0" started-at="2018-09-26T10:12:45Z" finished-at="2018-09-26T10:12:45Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- sub -->
        <test-method status="PASS" signature="sum()[pri:0, instance:calculator.calcy4@3567135c]" name="sum" duration-ms="0" started-at="2018-09-26T10:12:45Z" finished-at="2018-09-26T10:12:45Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- sum -->
      </class> <!-- calculator.calcy4 -->
    </test> <!-- demo -->
  </suite> <!-- mavendemo -->
</testng-results>
